### ISSUE TITLE
RegularExpressionLiteral parse incorrect

### ISSUE THREAD

**Issue by noootwo** [lydell/js-tokens#52]
```/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/``` 
This case will be parsed to ```/^[a-zA-Z0-9.!#$%&'*+/``` and something else.

But it can be correctly identified in javascript runtime.

**Comment by lydell** [comment]
Fix released in v9.0.1.

Thank you for reporting!
