### ISSUE TITLE
js-tokens can not match variables in template string.

### ISSUE THREAD

**Issue by janryWang** [lydell/js-tokens#7]
like this

```
jsTokens.exec("`hello world ${variable + `a + ${b}`} `")

```

Under normal circumstances, it can match `variable` and `b`

**Comment by lydell** [comment]
https://github.com/lydell/js-tokens/blob/54549dd979142c78cf629b51f9f06e8133c529f9/README.md#template-string-interpolation

**Comment by janryWang** [comment]
fine ,but

```
jsToken.exec("`hello world ${`{{{{{$1111111`}`   ddddddd")
```

will not match  `hello world ${`{{{{{$1111111`}`  and `ddddddd`

**Comment by lydell** [comment]
It's explained in the same link as well:

>  Only one level of nesting is supported.

**Comment by janryWang** [comment]
Ok , thx
